### ISSUE TITLE
Fortran modules installed in wrong place

### ISSUE THREAD

**Issue by dcesari** [ARPA-SIMC/eccodes-rpm#1]
Old problem: `eccodes.mod` and `grib_api.mod` are installed in `/usr/include`and not in `%{libdir}/$FC` (`/usr/lib64/gfortran`), on CentOS (and probably on Fedora as well).

**Comment by brancomat** [comment]
fixed on `eccodes-devel-2.7.0-2` (new version in repo and installed on `sette`)
