### ISSUE TITLE
python2-eccodes will be removed from Fedora 30

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/eccodes-rpm#7]
From https://src.fedoraproject.org/rpms/eccodes/raw/master/f/eccodes.spec:

> (1) Note: for now only a python2 interface is provided by upstream,
> and since Fedora is phasing out python2 this interface has
> been removed from this package starting with Fedora 30.
> As soon as upstream provides a python3 interface that one will
> be added here.

Unfortunately, ECMWF hasn't released yet a Python3 version of the library. We can wait or check if the debian patch (https://packages.debian.org/unstable/python3-eccodes) is more stable than a few months ago.

**Comment by brancomat** [comment]
update - from:
https://src.fedoraproject.org/rpms/eccodes/blob/master/f/eccodes.spec:

```
(1) Note: the python3 interface is provided by upstream,
but it fails unittesting, so it has been disabled for now.
As soon as this is fixed by upstream it will be added here.
```
python2 has already been removed from f28 so right now we're without eccodes python interface.

**Comment by brancomat** [comment]
Unless I'm missing something this was fixed some time ago by https://github.com/ARPA-SIMC/python-eccodes-rpm
